removes outline on help icon
hurtigruten/svelte-table pull request #8
Opened 2021-09-09 09:31 UTC by mariussd

When clicked, the help icon no longer leaves a black outline after the mouse has moved away.

2021-09-09 12:20 UTC, bartektelec approved these changes

2021-09-09 12:23 UTC, bartektelec requested changes
It's fine to remove the outline on focus for buttons, but you should however provide an alternative way of presenting the button in it's focused state. If you only remove the outline you will not be able to see if it's focused when using keyboard navigation.
Every button should have a hover, active and focus style.

Could we add a prop for styling that button instead?

2021-09-09 12:24 UTC, Fedoskina approved these changes

2021-09-13 12:22 UTC, mariussd commented
changed to using a style prop now, so the pull request doesn't entirely remove the outline, but provides a way to remove it

2021-09-13 14:36 UTC, emilps approved these changes
Looks good! One more tailwind class removed 💯

2021-09-13 18:49 UTC, bartektelec commented
![giphy (1)](https://user-images.githubusercontent.com/20260038/133139878-19388f2e-da9a-4f0b-8168-ac7561bd6f04.gif)
I like what i see

2021-09-13 18:49 UTC, bartektelec approved these changes

2021-09-13 19:12 UTC, neonwarp approved these changes

2021-09-13 19:13 UTC, merged